version: '3.8'
services:
  spring-boot:
    build: .
    image: g5maverick:latest
    ports:
      - "8080:8080"
    networks:
      - my-network
    volumes:
      - .:/app
  neo4j:
    image: neo4j:5.4.0
    environment:
      NEO4J_AUTH: 'neo4j/password'
    ports:
      - "7687:7687"
      - "7474:7474"
    networks:
      - my-network
networks:
  my-network:
